Show a splash screen when start the app
Brightcoders-Bootcamps/conferencias-app-OwenRamire pull request #3
Opened 2020-07-02 22:27 UTC by OwenRamire

![screen-20200702-215928_2](https://user-images.githubusercontent.com/42794917/86413676-70f60680-bc87-11ea-9eba-c03a4e6009ec.gif)

When this app is starting, we are going to see a splash screen of the app icon

2020-07-06 22:59 UTC, xErikPsx commented
Prueba

2020-07-06 23:00 UTC, xErikPsx commented
Prueba

2020-07-07 21:54 UTC, Loored requested changes

2020-07-07 21:54 UTC, Loored commented on OwenConferenciasApp/screens/formsLogin/MainLoginLayout.js
> +    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' , backgroundColor:'#F0F1F6'}}>
I suggest to wrap it in a class so it makes the code easy to read. 😄

2020-07-07 21:56 UTC, Loored requested changes

2020-07-07 21:56 UTC, Loored commented on OwenConferenciasApp/screens/ProfileUserLayout.js
> +import {View, Image, TouchableOpacity, Text, StyleSheet, Alert} from 'react-native';
Here you are calling the Alert component and not using it. Let's call only the components we need. 🙏

2020-07-07 21:56 UTC, Loored commented on OwenConferenciasApp/screens/ProfileUserLayout.js
> +            <Text style={{color: 'white', fontWeight: 'bold'}}>Edit Profile</Text>
You can wrap it in a class for this text. It just minimal details! 😄

2020-07-07 21:58 UTC, Loored approved these changes
Well done! 💯

2020-07-10 21:11 UTC, JCarlosRom approved these changes
Everything looks good

2020-07-15 19:45 UTC, luisarmandodv approved these changes

2020-07-15 19:45 UTC, merged